### ISSUE TITLE
how to compile this project using g++?

### ISSUE THREAD

**Issue by wujsy** [cotinyang/MRCP-Plugin-Demo#2]
Hi, I want to use some C++ third-party libs in this project, could I use g++ to compile this project, how should i modify?

**Comment by cotinyang** [comment]
Modify the Makefile.am in the plugin dir.
`AM_CPPFLAGS                = $(UNIMRCP_PLUGIN_INCLUDES) -std=c++11`
This worked for me.

**Comment by wujsy** [comment]
@cotinyang   thanks
